package RandomCircles;

import de.ur.mi.oop.app.GraphicsApp;
import de.ur.mi.oop.colors.Color;
import de.ur.mi.oop.colors.Colors;
import de.ur.mi.oop.graphics.Circle;
import de.ur.mi.oop.graphics.Point;

import java.util.Random;

public class RandomCircles extends GraphicsApp {

    /* Private Konstanten */
    private static final int CANVAS_HEIGHT = 800;
    private static final int CANVAS_WIDTH = 800;
    private static final int FRAME_RATE = 60;
    private static final Color BACKGROUND_COLOR = Colors.WHITE;
    private static final int MAX_CIRCLES = 100;
    private static final int MIN_CIRCLE_WIDTH = 5;
    private static final int MAX_CIRCLE_WIDTH = 50;

    private static final Random rand = new Random();


    /*
     * Die initialize-Methode wird einmalig zum Start des Programms
     * aufgerufen.
     */

    @Override
    public void initialize() {
        setupCanvas();
    }

    /*
     * Die draw-Methode wird so lange wiederholt aufgerufen, bis das Programm
     * beendet wird.
     */

    @Override
    public void draw() {
        drawBackground(BACKGROUND_COLOR);
        drawCircles();
    }

    private void setupCanvas() {
        setCanvasSize(CANVAS_WIDTH, CANVAS_HEIGHT);
        setFrameRate(FRAME_RATE);
    }

    private int getRandomBoundedInt(int min, int max) {
        return rand.nextInt(max - min) + min;
    }

    private void drawCircles() {
        for (int i = 0; i < MAX_CIRCLES; i++) {
            drawCircle();
        }
    }

    /**
     * Draws a single circle using random values, generated by getNextColor(), getNextDiameter() and getNextPoint()
     */
    private void drawCircle() {
        Color color = getNextColor();
        int diameter = getNextDiameter();
        Point center = getNextPoint(diameter);

        Circle circle = new Circle(center, diameter, color);
        circle.draw();
    }

    /**
     * Returns a random color for a new circle
     * @return A random color (Color), generated by using the RandomGenerator instance
     */
    private Color getNextColor() {
        return Colors.getRandomColor();
    }

    /**
     * Returns a random diameter for a new circle
     * @return A random diameter (int),  generated by using the RandomGenerator instance and
     * MIN_CIRCLE_WIDTH and MAX_CIRCLE_WIDTH as lower and upper limits
     */
    private int getNextDiameter() {
        return getRandomBoundedInt(MIN_CIRCLE_WIDTH, MAX_CIRCLE_WIDTH);
    }

    /**
     * Returns a random center point for a new circle
     * @param diameter Diameter of the new circle, used to generate a random position within the canvas boundaries
     * @return A random position (Point) within the canvas
     */
    private Point getNextPoint(int diameter) {
        int lowerX = diameter / 2;
        int upperX = CANVAS_WIDTH - (diameter / 2);
        int lowerY = diameter / 2;
        int upperY = CANVAS_HEIGHT - (diameter / 2);

        int x = getRandomBoundedInt(lowerX, upperX);
        int y = getRandomBoundedInt(lowerY, upperY);
        return new Point(x, y);
    }
}